export const cities = [
  "Casablanca",
  "Rabat",
  "Fez",
  "Marrakesh",
  "Tangier",
  "Agadir",
  "Meknes",
  "Oujda",
  "Kenitra",
  "Tetouan",
  "Temara",
  "Safi",
  "Mohammedia",
  "Khouribga",
  "El Jadida",
  "Beni Mellal",
  "Aït Melloul",
  "Nador",
  "Dar Bouazza",
  "Settat",
  "Berrechid",
  "Khemisset",
  "Inezgane",
  "Ksar El Kebir",
  "Larache",
  "Guelmim",
  "Khenifra",
  "Berkane",
  "Taourirt",
  "Bouskoura",
  "Fquih Ben Salah",
  "Dcheira El Jihadia",
  "Oued Zem",
  "El Kelaa Des Sraghna",
  "Errachidia",
  "Guercif",
  "Oulad Teima",
  "Ben Guerir",
  "Tifelt",
  "Lqliaa",
  "Taroudant",
  "Sefrou",
  "Essaouira",
  "Azrou",
  "Chefchaouen",
  "Midelt",
  "Zagora",
  "Ouarzazate",
  "Tinghir",
  "Asilah",
  "Sidi Ifni",
  "Tan-Tan",
  "Smara",
  "Laâyoune",
  "Dakhla",
  "Tarfaya",
  "Boujdour",
  "Jerada",
  "Martil",
  "Al Hoceima",
  "Sidi Bennour",
  "Sidi Kacem",
  "Sidi Yahya El Gharb",
  "Skhirat",
  "Témara",
  "Youssoufia",
  "Azilal",
  "Boulemane",
  "Chichaoua",
  "El Hajeb",
  "Figuig",
  "Ifrane",
  "Kelaat Sraghna",
  "Ouezzane",
  "Rehamna",
  "Sidi Slimane",
  "Tata",
  "Taza",
  "Tiznit",
];
